version: 1.0.{build}
image: Visual Studio 2017
build:
  verbosity: minimal

before_build:
  – dotnet restore -v Minimal

build:
  - dotnet build
  
  # build cache to preserve files/folders between builds
cache:
  - packages -> **\packages.config  # preserve "packages" directory in the root of build folder but will reset it if packages.config is modified
  - projectA\libs
  - node_modules                    # local npm modules
  - '%LocalAppData%\NuGet\Cache'    # NuGet < v3
  - '%LocalAppData%\NuGet\v3-cache' # NuGet v3